name: Build and Release

on:
  release:
    types: [published]

env:
  CURSEFORGE_ID: 1291505
  MODRINTH_ID: "c3gpeDZt"

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: get the name from pack.json
        id: props
        shell: bash
        run: |
            echo "name=$(cat pack.json | jq '.name' | tr -d '"')" >> $GITHUB_OUTPUT
            echo "version=$(cat pack.json | jq '.version' | tr -d '"')" >> $GITHUB_OUTPUT
            echo "mc-version=$(cat pack.json | jq '.mc_version' | tr -d '"')" >> $GITHUB_OUTPUT

      - name: create zip archive
        run: bash ./.github/archive.sh

      - name: Add files to GitHub-Release
        uses: shogo82148/actions-upload-release-asset@v1.7.5
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./${{ steps.props.outputs.name }}-*.zip"
          overwrite: true

      - name: publish to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
            modrinth-id: ${{ env.MODRINTH_ID }}
            modrinth-featured: true
            modrinth-unfeature-mode: intersection
            modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
            modrinth-name: "${{ steps.props.outputs.mc-version }} - ${{ steps.props.outputs.version }}"
            modrinth-version: "${{ steps.props.outputs.mc-version }}-${{ steps.props.outputs.version }}"
            curseforge-id: ${{ env.CURSEFORGE_ID }}
            curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
            curseforge-name: ""
            curseforge-version: ""
            version-type: "release"
            loaders: minecraft
            files: "./${{ steps.props.outputs.name }}-*.zip"
            changelog:  "${{ github.event.release.body }}"
            game-versions: "${{ steps.props.outputs.mc-version }}"
            game-version-filter: "releases"
